version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.8
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Abcd@1234}
      PGDATA: /data/postgres
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 128MB
    volumes:
       - postgres:/data/postgres
       - ./init:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
networks:
  postgres:
    driver: bridge

volumes:
    postgres: