apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: hrm-dev
data:
  redis.conf: |
    port 6379
    requirepass aart@2024
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes 