apiVersion: v1
kind: Service
metadata:
  name: sso-hrm-service
  namespace: hrm-dev
spec:
  type: NodePort
  ports:
    - port: 8150
      targetPort: 8150
      nodePort: 30150
  selector:
    app: sso-hrm
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sso-hrm-service
  namespace: hrm-dev
spec:
  serviceName: sso-hrm-service
  replicas: 2
  selector:
    matchLabels:
      app: sso-hrm
  template:
    metadata:
      labels:
        app: sso-hrm
    spec:
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: sso-hrm
        image: adh1502/hrm-sso-service:1.0.0
        ports:
        - containerPort: 8150
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        # database config
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://192.168.1.2:5432/elmich_factory"
        - name: SPRING_DATASOURCE_USERNAME
          value: "rfid_dev"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "aart@123"
        # Redis config
        - name: SPRING_REDIS_HOST
          value: "redis-hrm-service"  # Tên service của Redis trong K8s
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: SPRING_REDIS_PASSWORD
          value: "aart@2024"  # Thay thế bằng mật khẩu Redis của bạn
