version: '3'

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data:Z
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Abcd@1234
    command: server /data --console-address ":9001"
    restart: unless-stopped
    user: "root"
