version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: rabbit
    hostname: abbit
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Abcd@1234
      - RABBITMQ_ALLOW_ANONYMOUS=false
      - RABBITMQ_AUTH_MECHANISMS=PLAIN
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
    networks:
      - rabbitmq_network
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./logs:/var/log/rabbitmq
    privileged: true           # Thêm quyền privileged
    user: root                 # Chạy container với user root

networks:
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
